/*
 * BluSunrize
 * Copyright (c) 2017
 *
 * This code is licensed under "Blu's License of Common Sense"
 * Details can be found in the license file in the root folder of this project
 */

package blusunrize.immersiveengineering.common.entities;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The Hydraulic Crawler's resources.
 * <p>
 * An entity with a missing model or a missing texture is not an error Minecraft reports. It draws
 * the missing-texture chequer, or nothing at all, or -- nastiest, because it is silent -- something
 * that looks almost right: a UV a few pixels out lands on a neighbouring region and paints the
 * tracks with the cab's glazing.
 * <p>
 * <strong>The tests worth having here are the ones about two files agreeing.</strong> The model is
 * generated by {@code docs/tools/make_crawler_obj.py} and posed by {@code ModelHydraulicCrawler},
 * and the pivots, the wheel table and the belt's scroll period exist in both -- in Python and in
 * Java, because neither language can read the other's constants. Nothing at runtime would ever
 * notice those drifting apart: the machine would simply be drawn with its boom pinned somewhere it
 * is not, hitting blocks its picture says it cannot reach.
 */
class CrawlerAssetsTest
{
	private static final String ASSETS = "src/main/resources/assets/immersiveengineering/";
	private static final String MODEL_SRC =
			"src/main/java/blusunrize/immersiveengineering/client/models/ModelHydraulicCrawler.java";
	private static final String GENERATOR = "docs/tools/make_crawler_obj.py";
	private static final String OBJ = ASSETS+"models/entity/hydraulic_crawler.obj";

	private static String read(String path)
	{
		try
		{
			return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8);
		} catch(IOException e)
		{
			throw new AssertionError("could not read "+path, e);
		}
	}

	private static BufferedImage image(String relativePath)
	{
		File file = new File(ASSETS+relativePath);
		assertTrue(file.isFile(), "missing texture: "+file.getPath());
		try
		{
			BufferedImage image = javax.imageio.ImageIO.read(file);
			assertNotNull(image, "could not decode "+file.getPath());
			return image;
		} catch(IOException e)
		{
			throw new AssertionError("could not read "+file.getPath(), e);
		}
	}

	/**
	 * @return every number on the lines between the two markers, one row per line, ignoring
	 * anything after a comment marker
	 * <p>
	 * Used to read one table out of Java and the same table out of Python without either file
	 * having to be written in the other's shape.
	 */
	private static List<double[]> table(String source, String start, String end)
	{
		int from = source.indexOf(start);
		assertTrue(from >= 0, "could not find \""+start+"\"; the table has been renamed or "
				+"reformatted and this test is no longer reading it");
		int to = source.indexOf(end, from+start.length());
		assertTrue(to > from, "could not find the end of the table beginning at \""+start+"\"");
		List<double[]> rows = new ArrayList<>();
		Pattern number = Pattern.compile("-?\\d+(?:\\.\\d+)?");
		for(String line : source.substring(from+start.length(), to).split("\n"))
		{
			String code = line.split("//")[0].split("#")[0];
			Matcher m = number.matcher(code);
			List<Double> found = new ArrayList<>();
			while(m.find())
				found.add(Double.parseDouble(m.group()));
			if(found.isEmpty())
				continue;
			double[] row = new double[found.size()];
			for(int i = 0; i < row.length; i++)
				row[i] = found.get(i);
			rows.add(row);
		}
		return rows;
	}

	/**
	 * @return one of the generator's atlas regions as {@code x, y, w, h}
	 * <p>
	 * Read out of the Python rather than restated here, so a region that is moved on the sheet
	 * moves for this test too and the test keeps asking about the pixels it means to ask about.
	 */
	private static int[] region(String python, String name)
	{
		Matcher m = Pattern.compile("\""+name+"\"\\s*:\\s*\\((\\d+),\\s*(\\d+),\\s*(\\d+),\\s*(\\d+)\\)")
				.matcher(python);
		assertTrue(m.find(), "the generator has no region called \""+name+"\"");
		return new int[]{Integer.parseInt(m.group(1)), Integer.parseInt(m.group(2)),
				Integer.parseInt(m.group(3)), Integer.parseInt(m.group(4))};
	}

	/** @return the value of a {@code NAME = number} constant, in either language */
	private static double constant(String source, String name)
	{
		Matcher m = Pattern.compile(Pattern.quote(name)+"\\s*=\\s*(-?\\d+(?:\\.\\d+)?)")
				.matcher(source);
		assertTrue(m.find(), "no constant "+name+" to compare");
		return Double.parseDouble(m.group(1));
	}

	@Nested
	@DisplayName("the carried item")
	class Item
	{
		@Test
		@DisplayName("its model exists and points at a texture that exists")
		void modelAndTexture()
		{
			File model = new File(ASSETS+"models/item/hydraulic_crawler.json");
			assertTrue(model.isFile(), "missing item model: "+model.getPath());
			try(FileReader reader = new FileReader(model))
			{
				JsonObject json = new JsonParser().parse(reader).getAsJsonObject();
				String layer = json.getAsJsonObject("textures").get("layer0").getAsString();
				String path = "textures/"+layer.substring(layer.indexOf(':')+1)+".png";
				assertTrue(new File(ASSETS+path).isFile(), "missing item texture: "+path);
			} catch(IOException e)
			{
				throw new AssertionError("could not read "+model.getPath(), e);
			}
		}

		@Test
		@DisplayName("it has a name, or the creative tab shows a translation key")
		void hasAName()
		{
			assertTrue(read(ASSETS+"lang/en_us.lang")
							.contains("item.immersiveengineering.hydraulic_crawler.name="),
					"no name for the crawler item");
		}

		@Test
		@DisplayName("the no-room message it sends is translated")
		void chatKeyExists()
		{
			//An untranslated status message shows the raw key over the hotbar, which reads as a crash
			//rather than as a refusal.
			assertTrue(read(ASSETS+"lang/en_us.lang")
							.contains("chat.immersiveengineering.info.crawlerNoRoom="),
					"ItemHydraulicCrawler sends crawlerNoRoom but nothing translates it");
		}

		@Test
		@DisplayName("it is craftable")
		void isCraftable()
		{
			File recipe = new File(ASSETS+"recipes/vehicles/hydraulic_crawler.json");
			assertTrue(recipe.isFile(), "no recipe, so the machine is creative-only");
		}
	}

	@Nested
	@DisplayName("the entity sheet")
	class Sheet
	{
		@Test
		@DisplayName("it exists and is the size the model declares")
		void matchesDeclaredSize()
		{
			BufferedImage sheet = image("textures/entity/hydraulic_crawler.png");
			String source = read(MODEL_SRC);
			assertEquals((int)constant(source, "SHEET_WIDTH"), sheet.getWidth(),
					"the sheet is not as wide as ModelHydraulicCrawler says it is, so every UV "
							+"in the model is scaled against the wrong number of pixels");
			assertEquals((int)constant(source, "SHEET_HEIGHT"), sheet.getHeight(),
					"the sheet is not as tall as ModelHydraulicCrawler says it is");
		}

		@Test
		@DisplayName("it is the size the generator lays regions out on")
		void matchesGenerator()
		{
			BufferedImage sheet = image("textures/entity/hydraulic_crawler.png");
			double declared = constant(read(GENERATOR), "SHEET");
			assertEquals((int)declared, sheet.getWidth(), "the generator lays out a different sheet");
			assertEquals((int)declared, sheet.getHeight(), "the generator lays out a different sheet");
		}

		@Test
		@DisplayName("the cab glazing is painted with an alpha you can see through")
		void glazingIsTransparent()
		{
			//	=================================
			//	The test that would have caught an opaque windscreen.
			//	=================================
			//
			// The cab's windows are real openings in real steel and the renderer draws them in a
			// blended pass, and neither of those does anything at all if the texels are painted
			// opaque -- which is how they shipped, and what the operator reported as not being
			// able to see out while driving. Nothing at runtime says so; the machine simply has
			// blue-grey walls where its windows are.
			BufferedImage sheet = image("textures/entity/hydraulic_crawler.png");
			int[] glass = region(read(GENERATOR), "glass");
			int partial = 0;
			for(int y = glass[1]; y < glass[1]+glass[3]; y++)
				for(int x = glass[0]; x < glass[0]+glass[2]; x++)
				{
					int alpha = (sheet.getRGB(x, y) >>> 24)&0xFF;
					assertTrue(alpha > 0, "the glazing at "+x+","+y+" is fully transparent, which is "
							+"a hole in the cab rather than a window");
					assertTrue(alpha < 255, "the glazing at "+x+","+y+" is fully opaque, so the cab "
							+"cannot be seen out of no matter how the glass group is blended");
					//A tint dark enough to read as glass and light enough to drive through.
					if(alpha >= 0.25*255&&alpha <= 0.55*255)
						partial++;
				}
			assertTrue(partial > glass[2]*glass[3]/2,
					"only "+partial+" of "+(glass[2]*glass[3])+" glazing texels are in the band a "
							+"window is tinted at; the rest are so faint or so solid that the pane "
							+"reads as absent or as a wall");
		}

		@Test
		@DisplayName("nothing but the glazing is see-through")
		void everythingElseIsOpaque()
		{
			//The other half, and the opposite failure: a partial alpha anywhere the machine is
			//drawn in its opaque pass is a hole in the bodywork or a panel dimmed by the sky
			//behind it, depending on which threshold eats it. Only the glass may blend.
			BufferedImage sheet = image("textures/entity/hydraulic_crawler.png");
			String python = read(GENERATOR);
			int[] glass = region(python, "glass");
			for(String name : new String[]{"yellow", "steel", "cab_side", "walkway", "belt", "trim"})
			{
				int[] r = region(python, name);
				for(int y = r[1]; y < r[1]+r[3]; y++)
					for(int x = r[0]; x < r[0]+r[2]; x++)
						assertEquals(255, (sheet.getRGB(x, y) >>> 24)&0xFF,
								"region "+name+" at "+x+","+y+" is not opaque, and it is drawn in a "
										+"pass that does not blend");
			}
			assertTrue(glass[2] > 0&&glass[3] > 0, "the glazing region has no pixels in it");
		}
	}

	@Nested
	@DisplayName("the model")
	class Model
	{
		/**
		 * @return the OBJ's group names, in file order
		 */
		private List<String> groups()
		{
			List<String> names = new ArrayList<>();
			Matcher m = Pattern.compile("(?m)^o (\\S+)").matcher(read(OBJ));
			while(m.find())
				names.add(m.group(1));
			return names;
		}

		@Test
		@DisplayName("it exists, and is quads with texture coordinates on every corner")
		void wellFormed()
		{
			File file = new File(OBJ);
			assertTrue(file.isFile(), "missing model: "+OBJ+" -- run "+GENERATOR);
			int positions = 0, uvs = 0, faces = 0;
			for(String line : read(OBJ).split("\n"))
			{
				String[] parts = line.trim().split("\\s+");
				if(parts[0].equals("v"))
					positions++;
				else if(parts[0].equals("vt"))
				{
					uvs++;
					for(int i = 1; i <= 2; i++)
					{
						double value = Double.parseDouble(parts[i]);
						assertTrue(value >= -1e-6&&value <= 1+1e-6,
								"a texture coordinate of "+value+" is outside the sheet, so "
										+"whatever it lands on is a wrap of the whole texture");
					}
				}
				else if(parts[0].equals("f"))
				{
					faces++;
					assertEquals(5, parts.length,
							"EntityOBJModel reads quads and nothing else, and this face has "
									+(parts.length-1)+" corners");
					for(int i = 1; i < parts.length; i++)
					{
						String[] indices = parts[i].split("/");
						assertEquals(2, indices.length,
								"a face corner without exactly one texture coordinate: "+parts[i]);
						assertTrue(Integer.parseInt(indices[0]) <= positions,
								"a face uses vertex "+indices[0]+" before it is declared");
						assertTrue(Integer.parseInt(indices[1]) <= uvs,
								"a face uses texture coordinate "+indices[1]+" before it is declared");
					}
				}
			}
			assertTrue(faces > 500, "only "+faces+" faces; this is meant to be the detailed model "
					+"that replaced nine boxes");
		}

		@Test
		@DisplayName("every group the renderer draws is in it, and every group in it is drawn")
		void groupsMatchTheRenderer()
		{
			//	=================================
			//	The one failure mode a generated model has.
			//	=================================
			//
			// A group the renderer asks for and the file does not have is a piece of the machine
			// that silently is not drawn -- EntityOBJModel returns nothing rather than throwing,
			// because throwing inside a render loop is a client that cannot be played. So the
			// missing tracks, or the missing arm, would be reported as "it looks wrong" and
			// nothing else. Both directions are checked: a group in the file that nothing draws
			// is steel nobody will ever see, and is just as much a mistake.
			Set<String> expected = new LinkedHashSet<>();
			expected.add("undercarriage");
			expected.add("house");
			//The cab glazing, which is the house's own geometry kept in a group of its own so
			//the renderer can draw it last with blending on.
			expected.add("house_glass");
			expected.add("boom");
			expected.add("stick");
			for(String side : new String[]{"left", "right"})
			{
				expected.add("track_"+side);
				for(int i = 0; i < table(read(MODEL_SRC), "WHEELS = {", "};").size(); i++)
					expected.add("wheel_"+side+"_"+i);
			}
			for(CrawlerAttachment attachment : CrawlerAttachment.VALUES)
				//The same name ModelHydraulicCrawler.groupFor builds, kept as a string here so
				//this test never has to load a client-only class.
				expected.add("tool_"+attachment.getName());

			List<String> found = groups();
			for(String group : expected)
				assertTrue(found.contains(group),
						"the renderer draws \""+group+"\" and the model has no such group, so that "
								+"part of the machine is invisible");
			for(String group : found)
				assertTrue(expected.contains(group),
						"the model has a group \""+group+"\" that nothing draws");
		}

		@Test
		@DisplayName("the glazing group is drawn last, blended, and the state is put back")
		void glassIsDrawnLastAndBlended()
		{
			//	=================================
			//	Half of "see-through" is the texture and half is this pass.
			//	=================================
			//
			// A sheet painted with real alpha drawn without blending is opaque paint, which is
			// what the cab shipped as. This reads the source rather than running it because
			// ModelHydraulicCrawler is client-only and every line of it is GL state, but the
			// three things that can silently go missing are all visible in the text: the pass
			// existing at all, it happening after the opaque groups, and it being handed back.
			String java = read(MODEL_SRC);
			assertTrue(java.contains("\"house_glass\""),
					"nothing in the model names the glazing group, so the cab has no windows");

			int enable = java.indexOf("enableBlend");
			int draw = java.indexOf("model.render(HOUSE_GLASS)");
			int restore = java.indexOf("alphaFunc", draw+1);
			int disable = java.indexOf("disableBlend");
			assertTrue(enable >= 0, "the glazing is never blended, so its alpha does nothing");
			assertTrue(draw > enable, "the glazing group is drawn outside the blended pass");
			assertTrue(restore > draw&&restore < disable,
					"the alpha threshold the glass pass lowers is never put back, so every entity "
							+"drawn after the crawler keeps texels the world means to discard");
			assertTrue(disable > draw,
					"blending is left on after the crawler, which tints every entity and every "
							+"piece of HUD drawn after it");

			int glassPass = java.indexOf("renderGlass();");
			int lastOpaque = java.lastIndexOf("model.render(groupFor(attachment))");
			assertTrue(glassPass > lastOpaque&&lastOpaque > 0,
					"the glass is drawn before the arm, so whatever the blend should have shown "
							+"through it had not been drawn yet");
		}
	}

	@Nested
	@DisplayName("the model and its generator")
	class Agreement
	{
		@Test
		@DisplayName("they pivot the arm and the house in the same places")
		void pivots()
		{
			//	=================================
			//	Why this is the most important test in the file.
			//	=================================
			//
			// The arm's hitboxes are placed by CrawlerArm.alongArm, from the boom's pivot, in model
			// units. The server destroys blocks around the tool's tip computed the same way. The
			// model is a picture of all that, and the picture is generated by a script that cannot
			// read CrawlerGeometry. If the two ever disagree the machine still works perfectly --
			// it simply breaks blocks somewhere other than where its bucket is drawn, which is the
			// one bug in this feature nobody would forgive and the one nothing else would catch.
			String java = read(MODEL_SRC), python = read(GENERATOR);
			assertEquals(constant(python, "SLEW_HEIGHT"), constant(java, "SLEW_HEIGHT"), 1e-6,
					"the house is drawn turning about a different height than it is authored at");
			double[] boom = table(python, "BOOM_PIVOT = (", ")").get(0);
			assertEquals(boom[0], constant(java, "BOOM_PIVOT_X"), 1e-6, "the boom's pivot has moved");
			assertEquals(boom[1], constant(java, "BOOM_PIVOT_Y"), 1e-6, "the boom's pivot has moved");
			assertEquals(boom[2], constant(java, "BOOM_PIVOT_Z"), 1e-6, "the boom's pivot has moved");
			assertEquals(constant(python, "BELT_PERIOD"), constant(java, "BELT_PERIOD"), 1e-6,
					"the tracks are scrolled by a period the belt strip is not painted at, so the "
							+"tread jumps once per period instead of running");
		}

		@Test
		@DisplayName("the arm is drawn at the lengths the solver uses")
		void armLengths()
		{
			//The Java reads these from CrawlerGeometry; the generator cannot, so it restates them.
			String python = read(GENERATOR);
			assertEquals(CrawlerGeometry.BOOM_LENGTH, constant(python, "BOOM_LENGTH"), 1e-6,
					"the boom is drawn at a length the inverse kinematics does not solve for");
			assertEquals(CrawlerGeometry.STICK_LENGTH, constant(python, "STICK_LENGTH"), 1e-6,
					"the stick is drawn at a length the inverse kinematics does not solve for");
			assertEquals(CrawlerGeometry.TOOL_LENGTH, constant(python, "TOOL_LENGTH"), 1e-6,
					"the tool is drawn at a length the inverse kinematics does not solve for");
			assertEquals(CrawlerGeometry.TRACK_CENTRE, constant(python, "WHEEL_X"), 1e-6,
					"the tracks are wound on about a different centreline than they are drawn at");
		}

		@Test
		@DisplayName("they place and size every wheel identically")
		void wheels()
		{
			List<double[]> java = table(read(MODEL_SRC), "WHEELS = {", "};");
			List<double[]> python = table(read(GENERATOR), "WHEELS = [", "]");
			assertEquals(python.size(), java.size(),
					"one table has "+python.size()+" wheels and the other "+java.size()+", so some "
							+"wheel is either drawn without being turned or turned without existing");
			assertTrue(java.size() >= 4, "found only "+java.size()+" wheels; the tables have "
					+"probably been reformatted out from under this test");
			for(int i = 0; i < java.size(); i++)
			{
				//The generator's rows carry a fourth number, the wheel's width, which nothing in the
				//renderer needs: a wheel turns about its axle and how thick it is never comes into it.
				assertEquals(python.get(i)[0], java.get(i)[0], 1e-6, "wheel "+i+" is at a different z");
				assertEquals(python.get(i)[1], java.get(i)[1], 1e-6, "wheel "+i+" is at a different y");
				assertEquals(python.get(i)[2], java.get(i)[2], 1e-6,
						"wheel "+i+" is a different size, so it is turned at the wrong rate and "
								+"visibly slips against the ground");
			}
		}
	}
}
