/*
 * BluSunrize
 * Copyright (c) 2017
 *
 * This code is licensed under "Blu's License of Common Sense"
 * Details can be found in the license file in the root folder of this project
 */

package blusunrize.immersiveengineering.api.energy.wires;

import blusunrize.immersiveengineering.api.energy.wires.ImmersiveNetHandler.Connection;
import net.minecraft.util.math.BlockPos;

import java.util.*;
import java.util.function.Predicate;

/**
 * Finds wires whose endpoint blocks are gone.
 * <p>
 * IE keeps wires in world save data, apart from the blocks they hang between. Anything that removes a
 * connector without telling IE -- a WorldEdit or FAWE delete or paste, a chunk regenerated by hand -- leaves
 * the connection behind: invisible, never cleaned up unless {@code validateConnections} is on (and that
 * option loads every endpoint chunk at startup, which a large map cannot afford), and still walked by every
 * route search that reaches it.
 * <p>
 * An endpoint is classified without loading anything:
 * <ul>
 * <li><b>Missing</b> -- its chunk is loaded and there is no connectable block there. Certain.</li>
 * <li><b>Unproxied</b> -- its chunk is not loaded and no proxy was saved for it. Suspect, never certain: a block
 * deleted while loaded looks like this, but so does a real connector that was loaded when a server built before
 * {@link ImmersiveNetHandler#proxiesToSave()} stopped. The only way to settle one is to load its chunk.</li>
 * </ul>
 * Pure logic over predicates, so it is tested without a world.
 *
 * @author LDImmersiveEngineering -- wire maintenance
 */
public final class GhostConnectionAudit
{
	private GhostConnectionAudit()
	{
	}

	public static final class Result
	{
		/** Connections with at least one endpoint certainly missing. */
		public final List<Connection> missing = new ArrayList<>();
		/** Connections not known to be broken but with an endpoint that is unloaded and has no proxy. */
		public final List<Connection> unproxied = new ArrayList<>();
		public int inspected;
		public final Set<BlockPos> missingNodes = new HashSet<>();
		public final Set<BlockPos> unproxiedNodes = new HashSet<>();
	}

	/**
	 * @param connections  every connection in the dimension; both directions may appear, and a connection and
	 *                     its reverse are reported once
	 * @param loaded       whether a position's chunk is loaded
	 * @param connectable  whether a loaded position holds a connectable block
	 * @param proxied      whether a proxy exists for a position
	 */
	public static Result audit(Collection<Connection> connections, Predicate<BlockPos> loaded,
							   Predicate<BlockPos> connectable, Predicate<BlockPos> proxied)
	{
		Result result = new Result();
		Set<List<Long>> seen = new HashSet<>();
		for(Connection con : connections)
		{
			long a = con.start.toLong(), b = con.end.toLong();
			//One entry per wire, whichever direction it was stored in, and per conductor set so a bundle and a
			//wire between the same two boxes are both considered.
			List<Long> key = Arrays.asList(Math.min(a, b), Math.max(a, b), con.isBundle()?1L: 0L);
			if(!seen.add(key))
				continue;
			result.inspected++;
			State s = state(con.start, loaded, connectable, proxied);
			State e = state(con.end, loaded, connectable, proxied);
			if(s==State.MISSING||e==State.MISSING)
			{
				result.missing.add(con);
				if(s==State.MISSING)
					result.missingNodes.add(con.start);
				if(e==State.MISSING)
					result.missingNodes.add(con.end);
			}
			else if(s==State.UNPROXIED||e==State.UNPROXIED)
			{
				result.unproxied.add(con);
				if(s==State.UNPROXIED)
					result.unproxiedNodes.add(con.start);
				if(e==State.UNPROXIED)
					result.unproxiedNodes.add(con.end);
			}
		}
		return result;
	}

	enum State
	{
		PRESENT, MISSING, UNPROXIED
	}

	static State state(BlockPos pos, Predicate<BlockPos> loaded, Predicate<BlockPos> connectable,
					   Predicate<BlockPos> proxied)
	{
		if(loaded.test(pos))
			return connectable.test(pos)?State.PRESENT: State.MISSING;
		return proxied.test(pos)?State.PRESENT: State.UNPROXIED;
	}
}
